# scene: engine\test\viviModel\scene #engine\modelPreview\scene #gameplayScene
# scene: engine\test\pbrScene\scene #engine\modelPreview\scene #gameplayScene
scene: scenes\first_test
maximumDeltaTime: 0.05
fixedDeltaTime: 0.016666666666
fullscreen: false
debugSceneLoading: false
vsync: false
godMode: true
soundEnabled: false
showFps: true
msaa: 0
debugGraphics: false
libraries:
  - Butterfly.dll