# scene: engine\test\viviModel\scene #engine\modelPreview\scene #gameplayScene
# scene: engine\test\pbrScene\scene #engine\modelPreview\scene #gameplayScene
# scene: engine\test\sponza-gltf-pbr\scene
# scene: gameplayScene
scene: 'scenes\first_test.asset'
fullscreen: false
debugSceneLoading: false
godMode: true
soundEnabled: false
showFps: true
assetConvertionEnabled: true
librariesRoot: ""
libraries:
  - libButterfly.so
  # - Game.dll
mountAssets:
  - engine/assets
  # - build/assets.zip
  - assets
  # - build/assets_game.zip
  # - assets_no_compression.zip
mountLibraries:
  - library
