# scene: engine\test\viviModel\scene #engine\modelPreview\scene #gameplayScene
# scene: engine\test\pbrScene\scene #engine\modelPreview\scene #gameplayScene
scene: scenes\first_test
fullscreen: false
debugSceneLoading: false
vsync: true
godMode: true
soundEnabled: false
showFps: true
msaa: 0
debugGraphics: false
libraries:
  - Butterfly.dll