# scene: engine\test\viviModel\scene #engine\modelPreview\scene #gameplayScene
# scene: engine\test\pbrScene\scene #engine\modelPreview\scene #gameplayScene
# scene: engine\test\sponza-gltf-pbr\scene
scene: gameplayScene
fullscreen: false
debugSceneLoading: false
vsync: true
godMode: true
soundEnabled: false
showFps: true
msaa: 0
debugGraphics: false
libraries:
#  - Butterfly.dll
  - Game.dll
mountDirs:
  - engine/assets
  - assets
#  - assets.zip
#  - assets_no_compression.zip