local CellTypeInv = {
	"None",
	"Any",
	"Ground",
	"GroundWithGrass",
	"GroundPrepared",
	"Sphere",
	"Tree",
	"Wheat",
	"WheatCollected_1",
	"WheatCollected_2",
	"WheatCollected_3",
	"WheatCollected_4",
	"WheatCollected_5",
	"WheatCollected_6",
	"WheatPlanted_0",
	"WheatPlanted_1",
	"Wood",
	"Fence",
	"Stone",
	"Campfire",
	"CampfireWithWood",
	"CampfireWithWoodFired",
	"FlintStone",
	"Flour",
	"Stove",
	"StoveWithWood",
	"StoveWithWoodFired",
	"Bread_1",
	"Bread_2",
	"Bread_3",
	"Bread_4",
	"Bread_5",
	"Bread_6",
}

return CellTypeInv